# Generated by Django 4.2.30 on 2026-08-03 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_token', models.CharField(max_length=500)),
                ('user_id', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('jwt_token', models.TextField(blank=True, null=True)),
                ('jwt_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MEDA Session',
                'verbose_name_plural': 'MEDA Sessions',
            },
        ),
        migrations.CreateModel(
            name='ApiSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_month', models.CharField(max_length=20)),
                ('to_month', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('total_months', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meda_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Sync Job',
                'verbose_name_plural': 'API Sync Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, default='', max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.TextField()),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('records_received', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='meda_integration.apisyncjob')),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('raw_json', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_records', to='meda_integration.apirequestlog')),
            ],
            options={
                'verbose_name': 'API Raw Record',
                'verbose_name_plural': 'API Raw Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(blank=True, default='', max_length=150)),
                ('circle_name', models.CharField(blank=True, default='', max_length=150)),
                ('substation_code', models.CharField(blank=True, default='', max_length=100)),
                ('substation_name', models.CharField(blank=True, default='', max_length=200)),
                ('feeder_code', models.CharField(blank=True, default='', max_length=100)),
                ('generator_name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('agreement_capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('nce_generator_code', models.CharField(db_index=True, max_length=100)),
                ('metering_point_id', models.CharField(blank=True, default='', max_length=100)),
                ('agreement_id', models.CharField(db_index=True, max_length=100)),
                ('agreement_type', models.CharField(blank=True, default='', max_length=100)),
                ('agreement_type_description', models.CharField(blank=True, default='', max_length=255)),
                ('credit_note_type', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_commission', models.DateField(blank=True, null=True)),
                ('credit_note_from_date', models.DateField(blank=True, db_index=True, null=True)),
                ('credit_note_to_date', models.DateField(blank=True, db_index=True, null=True)),
                ('kwh_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('kwh_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('kwh_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rkvah_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('rkvah_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rkvah_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='meda_integration.apirawrecord')),
            ],
            options={
                'verbose_name': 'Energy Credit Note',
                'verbose_name_plural': 'Energy Credit Notes',
                'ordering': ['-credit_note_from_date', '-created_at'],
                'indexes': [models.Index(fields=['agreement_id'], name='meda_integr_agreeme_75fe53_idx'), models.Index(fields=['nce_generator_code'], name='meda_integr_nce_gen_3da839_idx'), models.Index(fields=['credit_note_from_date'], name='meda_integr_credit__47a655_idx'), models.Index(fields=['credit_note_to_date'], name='meda_integr_credit__35a896_idx'), models.Index(fields=['agreement_id', 'credit_note_from_date', 'credit_note_to_date'], name='meda_integr_agreeme_f0de3a_idx')],
            },
        ),
    ]
