# Generated by Django 4.2.30 on 2026-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('investor_name_and_address', models.TextField(blank=True, default='')),
                ('name_of_developer', models.CharField(blank=True, default='', max_length=255)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('village', models.CharField(blank=True, default='', max_length=255)),
                ('taluka', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Bagasse',
                'verbose_name_plural': 'Bagasse',
            },
        ),
        migrations.CreateModel(
            name='Biomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('investor_name_and_address', models.TextField(blank=True, default='')),
                ('name_of_developer', models.CharField(blank=True, default='', max_length=255)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('village', models.CharField(blank=True, default='', max_length=255)),
                ('taluka', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Biomass',
                'verbose_name_plural': 'Biomass',
            },
        ),
        migrations.CreateModel(
            name='MSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('investor_name_and_address', models.TextField(blank=True, default='')),
                ('name_of_developer', models.CharField(blank=True, default='', max_length=255)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('village', models.CharField(blank=True, default='', max_length=255)),
                ('taluka', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('grid_connected_offgrid', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'MSW',
                'verbose_name_plural': 'MSW',
            },
        ),
        migrations.CreateModel(
            name='SHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_taluka', models.CharField(blank=True, default='', max_length=255)),
                ('completed_hydro_electric_projects', models.CharField(blank=True, default='', max_length=255)),
                ('installed_capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('comissioning_year', models.CharField(blank=True, default='', max_length=50)),
                ('date_of_commissioning', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SHP',
                'verbose_name_plural': 'SHP',
            },
        ),
        migrations.CreateModel(
            name='SolarGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('developer_name', models.CharField(blank=True, default='', max_length=255)),
                ('commissioned_capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('project_location', models.CharField(blank=True, default='', max_length=255)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('power_sale_mode', models.CharField(blank=True, default='', max_length=255)),
                ('project_park', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Solar Grid',
                'verbose_name_plural': 'Solar Grids',
            },
        ),
        migrations.CreateModel(
            name='SolarKusum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('zone', models.CharField(blank=True, default='', max_length=255)),
                ('circle', models.CharField(blank=True, default='', max_length=255)),
                ('division', models.CharField(blank=True, default='', max_length=255)),
                ('subdivision', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('taluka', models.CharField(blank=True, default='', max_length=255)),
                ('village', models.CharField(blank=True, default='', max_length=255)),
                ('sub_station_code', models.CharField(blank=True, default='', max_length=255)),
                ('substation_description', models.TextField(blank=True, default='')),
                ('solar_capacity_as_per_ppa_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('solar_capacity_installed_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('balance_solar_capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('name_of_successful_bidder', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Solar Kusum',
                'verbose_name_plural': 'Solar Kusum',
            },
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('date_of_commissioned', models.DateField(blank=True, null=True)),
                ('gut_no', models.CharField(blank=True, default='', max_length=255)),
                ('taluka', models.CharField(blank=True, default='', max_length=255)),
                ('village', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Wind',
                'verbose_name_plural': 'Wind',
            },
        ),
    ]
