# Generated by Django 4.2.30 on 2026-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomass',
            name='commissioning_year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='biomass',
            name='day',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='biomass',
            name='month',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='biomass',
            name='quarter',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
