# Generated by Django 4.2.30 on 2026-09-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0002_biomass_commissioning_year_biomass_day_biomass_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomass',
            name='commissioned_date',
        ),
    ]
