# Generated by Django 4.2.30 on 2026-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0003_remove_biomass_commissioned_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtSolarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('division', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('taluka', models.CharField(blank=True, default='', max_length=255)),
                ('consumer_no', models.CharField(blank=True, default='', max_length=255)),
                ('building_name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('pin_code', models.CharField(blank=True, default='', max_length=50)),
                ('ownership_type', models.CharField(blank=True, default='', max_length=255)),
                ('capacity_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Government Building Solarization',
                'verbose_name_plural': 'Government Building Solarization',
            },
        ),
        migrations.AddField(
            model_name='msw',
            name='grid_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shp',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shp',
            name='region',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
