# Generated by Django 4.2.30 on 2026-09-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0004_govtsolarization_msw_grid_type_shp_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomass',
            name='commissioned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
