# Generated by Django 4.2.30 on 2026-09-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0005_biomass_commissioned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomass',
            name='commissioning_year',
        ),
        migrations.RemoveField(
            model_name='biomass',
            name='day',
        ),
        migrations.RemoveField(
            model_name='biomass',
            name='month',
        ),
        migrations.RemoveField(
            model_name='biomass',
            name='quarter',
        ),
    ]
