# Generated by Django 4.2.30 on 2026-09-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0008_solargrid_fields_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='wind',
            name='developer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wind',
            name='investor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wind',
            name='standardized_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
