# Generated by Django 4.2.30 on 2026-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0009_wind_developer_wind_investor_wind_standardized_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wind',
            name='developer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wind',
            name='gut_no',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wind',
            name='investor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wind',
            name='site_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
