# Generated by Django 4.2.30 on 2026-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0010_alter_wind_developer_alter_wind_gut_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solargrid',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
