# Generated by Django 4.2.30 on 2026-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0011_solargrid_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSKVY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('developer_name', models.CharField(blank=True, default='', max_length=255)),
                ('substation', models.CharField(blank=True, default='', max_length=255)),
                ('taluka', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Commissioned', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'MSKVY Solar Project',
                'verbose_name_plural': 'MSKVY Solar Projects',
            },
        ),
    ]
