# Generated by Django 4.2.30 on 2026-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_templates', '0012_mskvy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mskvy',
            options={'verbose_name': 'MSKVY', 'verbose_name_plural': 'MSKVY'},
        ),
        migrations.RenameField(
            model_name='mskvy',
            old_name='commissioned_date',
            new_name='commission_date',
        ),
        migrations.RenameField(
            model_name='mskvy',
            old_name='capacity_mw',
            new_name='commissioned_capacity_mw',
        ),
        migrations.RemoveField(
            model_name='mskvy',
            name='developer_name',
        ),
        migrations.RemoveField(
            model_name='mskvy',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='mskvy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mskvy',
            name='substation',
        ),
        migrations.RemoveField(
            model_name='mskvy',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='mskvy',
            name='year',
        ),
        migrations.AddField(
            model_name='mskvy',
            name='project_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mskvy',
            name='source',
            field=models.CharField(blank=True, default='MSKVY', max_length=255),
        ),
        migrations.AlterField(
            model_name='solargrid',
            name='source',
            field=models.CharField(blank=True, default='Solar', max_length=255),
        ),
    ]
